In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

In [11]:
arr1 = np.array([7, 8, 9, 10, 11, 12])
print("1D array: ", arr1)

1D array:  [ 7  8  9 10 11 12]


In [12]:
arr2 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("2D array: \n", arr2)

2D array: 
 [[10 20 30]
 [40 50 60]
 [70 80 90]]


In [13]:
arr = np.array([4, 5, 6])
print("Array with Rank 1: \n", arr)

Array with Rank 1: 
 [4 5 6]


In [14]:
arr = np.array([[2, 4, 6], [8, 10, 12]])
print("Array with Rank 2: \n", arr)

Array with Rank 2: 
 [[ 2  4  6]
 [ 8 10 12]]


In [15]:
arr = np.array((3, 6, 9))
print("\nArray created using passed tuple:\n", arr)


Array created using passed tuple:
 [3 6 9]


In [17]:
print("About arr2:")
print("Type\t\t:" ,type(arr2))
print("Datatype\t:", arr2.dtype)
print("Shape\t\t:", arr2.shape)
print("Size\t\t:", arr2.size)
print("itemsize\t:", arr2.itemsize)
print("No. of dim\t:", arr2.ndim)
print("No. of bytes\t:", arr2.nbytes)

About arr2:
Type		: <class 'numpy.ndarray'>
Datatype	: int32
Shape		: (3, 3)
Size		: 9
itemsize	: 4
No. of dim	: 2
No. of bytes	: 36


In [18]:
arr3 = np.zeros((5, 2), dtype=int)
arr4 = np.ones((3, 4), dtype=float)
arr5 = np.eye(4, 3)
arr6 = np.random.rand(3, 2)
arr7 = np.random.randint(10, size=(2, 6))
print("Zero Array \t:\n", arr3)
print("Arrays with unit values\t:\n", arr4)
print("Identity matrix\t:\n", arr5)
print("Random array\t\n", arr6)
print("Random integer array\t:\n", arr7)


Zero Array 	:
 [[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
Arrays with unit values	:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Identity matrix	:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
Random array	
 [[0.67793105 0.12553376]
 [0.5860874  0.60848967]
 [0.99059283 0.94592945]]
Random integer array	:
 [[9 5 4 0 0 6]
 [7 2 8 2 1 2]]


In [19]:
arr8 = np.arange(2, 20, 4)
print("Array created with arange: \t\n", arr8)

Array created with arange: 	
 [ 2  6 10 14 18]


In [21]:
arr9 = np.linspace(5, 15, 30)
print("Array created using linspace requesting 30 elements within 5 to 15:\t\n", arr9)

Array created using linspace requesting 30 elements within 5 to 15:	
 [ 5.          5.34482759  5.68965517  6.03448276  6.37931034  6.72413793
  7.06896552  7.4137931   7.75862069  8.10344828  8.44827586  8.79310345
  9.13793103  9.48275862  9.82758621 10.17241379 10.51724138 10.86206897
 11.20689655 11.55172414 11.89655172 12.24137931 12.5862069  12.93103448
 13.27586207 13.62068966 13.96551724 14.31034483 14.65517241 15.        ]


In [22]:
arr10 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]])
print(arr10)
print("Row 2:", arr10[1, :])
print("Column 2:", arr10[:, 3])
print("Elements 7, 8, 12, 13 :\n", arr10[1:3, 1:3])
print("All elements: \n", arr10[::])
print("Strides:\n", arr10[0::2, 1:3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Row 2: [ 6  7  8  9 10]
Column 2: [ 4  9 14 19]
Elements 7, 8, 12, 13 :
 [[ 7  8]
 [12 13]]
All elements: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Strides:
 [[ 2  3]
 [12 13]]


In [23]:
arr11 = np.array([2, 4, 6, 8, 10, 12, 14, 16, 18])
mask = np.array([1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=bool)
print(arr11[mask])

[ 2  6 10 14 18]


In [24]:
arr13 = np.array([5, 10, 15])
arr14 = np.array([20, 25, 30])
arr15 = arr13 + arr14
arr16 = arr13 - arr14
print("Summation:\t", arr15)
print("Difference:\t", arr16)

Summation:	 [25 35 45]
Difference:	 [-15 -15 -15]


In [25]:
arr17 = np.array([10, 20, 30, 40])
result7 = np.sin(arr17)
print("Sin values:\t", result7)
result8 = np.log(arr17)
print("Log value:\t", result8)

Sin values:	 [-0.54402111  0.91294525 -0.98803162  0.74511316]
Log value:	 [2.30258509 2.99573227 3.40119738 3.68887945]
